name: pharmaaccess
description: Fun and Knowledge for Healthcare World.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.7+4443

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  badges: ^1.1.1
  camera: ^0.5.4+2
  cupertino_icons: ^0.1.2
  curved_navigation_bar: 1.0.1
  cached_network_image: ^3.1.0
  charts_flutter: 0.12.0
  dartz: ^0.10.0-nullsafety.2
  device_info: ^2.0.2
  dropdown_search: ^0.6.1
  firebase_analytics: ^9.1.4
  firebase_crashlytics: ^2.5.0
#  firebase_dynamic_links: ^4.0.5
  firebase_messaging: ^11.2.6
  firebase_core: ^1.10.0
  flick_video_player: 0.3.1
  flutter_local_notifications: 9.4.0
  flutter_svg: 0.22.0
  font_awesome_flutter: 9.0.0
  http: 0.13.3
  image_picker: 0.8.1+4
  intl: ^0.17.0
  keyboard_actions: ^3.4.0
  multi_select_flutter: ^4.0.0
  get: 4.3.8
  syncfusion_flutter_calendar: 19.4.47
  #  outline_material_icons: ^0.1.1
  package_info: ^2.0.2
  path: 1.8.0
  path_provider: 2.0.0
  permission_handler: ^8.0.0+2
  polygon_clipper: ^1.0.2
  provider: 5.0.0
  qr_flutter: ^4.0.0
  random_string: 2.3.1
  rounded_loading_button: ^2.0.5
  #  searchable_dropdown: ^1.1.0
  share: 2.0.0
  shared_preferences: ^2.0.6
  spannable_grid: ^0.2.0
  #  splashscreen: ^1.2.0
  sqflite: ^2.0.0+3
  store_redirect: 2.0.0
  table_calendar: ^3.0.2
  uuid: ^3.0.4
  video_player: 2.0.2
  webview_flutter: 2.0.0
  url_launcher: ^6.0.9
  sn_progress_dialog: ^1.0.3
  fluttertoast: 8.0.2
  overlay_support: ^1.0.0
  #  odoo_api: ^1.0.4
  #flutter_unity_widget: ^0.1.6+8
  #flutter_unity_widget:
  #  path: ./vendors/flutter_unity_widget-0.1.6+8/
  #camera: ^0.5.8
  flutter_background_service: 0.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/app_icon_no_transparent.png"
#  image_path: "assets/icon/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/
    - assets/images/app_logo.png
    - assets/images/app_logo_small.png
    - assets/images/mountains.jpg
    - assets/images/icon_homepage.svg
    - assets/images/icon_brand.svg
    - assets/images/icon_club.svg
    - assets/images/icon_quiz.svg
    - assets/images/icon_game.svg
    - assets/images/icon_contact_us.svg
    - assets/images/icon_mic.svg
    - assets/images/icon_notification.svg
    - assets/images/cinfa_hexagon_small.png
    - assets/images/cinfa_hexagon_small_thin.png
    - assets/images/cinfa_hexagon_large.png
    - assets/images/ahmed_hassan.jpeg
    - assets/images/login_signup_background.jpg
    - assets/images/qatar_flag.png
    - assets/images/kuwait_flag.png
    - assets/images/united_arab_emirates_flag.png
    - assets/images/saudi_arabia_flag.png
    - assets/images/profile_placeholder.png
    - assets/images/product_loading.gif
    - assets/images/business_finance.png
    - assets/images/quiz_result.png
    - assets/images/social_home.svg
    - assets/images/earn_points.svg
    - assets/images/redeem_points.svg
    - assets/images/invite_friends.svg
    - assets/images/icon_registration.svg
    - assets/images/icon_quiz_round.svg
    - assets/images/icon_play_promotional.svg
    - assets/images/invite_friends_avatar.svg
    - assets/images/promo_code.svg
    - assets/images/game_landing.png
    - assets/images/contact_us.svg
    - assets/images/learning_quiz.png
    - assets/images/learning_educational_support.png
    - assets/images/icon_message_from_expert.png
    - assets/images/icon_share.png
    - assets/images/club.png
    - assets/images/educational.png
    - assets/images/calculator.png
    - assets/images/quiz.png
    - assets/images/icon_icpd.png
    - assets/images/icon_icpd_socrates.png
    - assets/images/icon_avicenna.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AverageSans
      fonts:
        - asset: assets/fonts/AverageSans-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    #    - asset: assets/fonts/OpenSans-Light.ttf
    #      weight: 300
    #    - asset: assets/fonts/OpenSans-Bold.ttf
    #      weight: 700
    #    - asset: assets/fonts/OpenSans-SemiBold.ttf
    #      weight: 600
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
